opencloud-eu/web

- packages/design-system/docs/.vitepress/theme/index.ts
This is necessary to document all components that use `vue3-gettext`.
> chore(design-system): initialize gettext for docs

- packages/web-runtime/src/components/Account/AppTokens.vue
- packages/web-runtime/src/components/Modals/AppTokenModal.vue
- packages/web-runtime/src/helpers/appTokens.ts
- packages/web-runtime/tests/unit/components/Account/AppTokens.spec.ts
- packages/web-runtime/tests/unit/components/Modals/AppTokenModal.spec.ts
Reworks the app tokens so a newly created token gets only shown once to the user. The user then can copy the token.
Follow-up after https://github.com/opencloud-eu/web/pull/43
refs https://github.com/opencloud-eu/web/issues/42
> feat(runtime): rework app tokens

- .vscode/settings.json
- dev/scripts/bump_versions.sh
- dev/scripts/create_and_push_tags.sh
- package.json
- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/vite.config.ts
- packages/eslint-config/README.md
- packages/eslint-config/package.json
- packages/extension-sdk/README.md
- packages/extension-sdk/package.json
- packages/prettier-config/README.md
- packages/prettier-config/package.json
- packages/tsconfig/README.md
- packages/tsconfig/package.json
- packages/web-client/README.md
- packages/web-client/package.json
- packages/web-pkg/README.md
- packages/web-pkg/package.json
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- packages/web-pkg/tsconfig.json
- packages/web-pkg/vite.config.ts
- packages/web-test-helpers/README.md
- packages/web-test-helpers/package.json
- packages/web-test-helpers/vite.config.ts
This doesn't include any CI pipelines since we don't have CI in place just yet. It just prepares all the packages to be published manually.
closes https://github.com/opencloud-eu/web/issues/209
> chore: prepare publishing of 1.0.0 packages

- deployments/examples/oc_web/docker-compose.yml
- docker-compose.yml
- change docker image name to `${OC_IMAGE:-opencloudeu/opencloud-rolling:latest}`
- downgraded collabora version to `CODE 24.04.12.2`. the last 24.04.12.4 https://www.collaboraonline.com/code-24-04-release-notes/?utm_source=chatgpt.com doesn;t work (checked also with opencloud_full)
> fix: change docker image name

- tests/e2e/cucumber/features/app-provider-onlyOffice/officeSuites.feature
- tests/e2e/cucumber/features/app-provider-onlyOffice/urlJourneys.feature
- tests/e2e/cucumber/features/app-provider/lock.feature
- tests/e2e/cucumber/features/app-provider/officeSuites.feature
- tests/e2e/cucumber/features/app-provider/secureView.feature
- tests/e2e/cucumber/features/app-provider/urlJourneys.feature
after https://github.com/opencloud-eu/web/pull/89 we can't run app-provider locally
I split the app provider into two parts: `app-provider` and `app-provider-onlyoffice`
> split e2e app-provider suite

- packages/web-app-epub-reader/tests/unit/__snapshots__/app.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/components/ItemFilter.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
- packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
- Fixes #214 
- test case 1:
- test case 2:
- ...
> Tiles view, replace sort select with less visual obstrutive filter-chip

- packages/web-app-admin-settings/src/components/AppTemplate.vue
- packages/web-app-admin-settings/tests/unit/components/AppTemplate.spec.ts
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-app-search/src/portals/SearchBar.vue
- packages/web-pkg/src/components/SideBar/SideBar.vue
- packages/web-runtime/src/components/Topbar/TopBar.vue
- packages/web-runtime/src/layouts/Application.vue
Reworks how the sidebars on the left and right behave on smaller screens to improve the mobile experience. The left sidebar now toggles automatically with smaller screen sizes. The right sidebar on the other hand only snaps on screens <580px.
As discussed with @tbsbdr , we currently don't care about the user setting for the left sidebar. That means resizing the screen could potentially expand the sidebar despite the user having it toggled in general. We can tackle this as soon as we correctly persist this setting.
Also fixes the search bar appearance in the mobile view and refactors 2 components to use script setup. So this PR is best reviewed by commits.
closes https://github.com/opencloud-eu/web/issues/212
> feat: mobile sidebars

- packages/web-pkg/src/components/SideBar/SideBar.vue
Fixes an issue where the file list would be blank if the sidebar is open and snapped (<580px screen width) and then increasing the window size.
> fix: empty file list

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-runtime/src/index.ts
- packages/web-runtime/src/pages/resolvePublicLink.vue
Fixes that public link page titles and OCM share page titles looked broken.
> fix: empty public link or OCM share page title

- tests/e2e/cucumber/features/admin-settings/spaces.feature
when we run tests parallel `RETRY=1 HEADLESS=true PARALLEL=4 ./run-e2e.sh --suites admin-settings` test was flaky because admin user had 2 similar` team A` spaces. fixed it
> fix test when admin creates spaces parallel

- packages/design-system/src/directives/OcTooltip.ts
- packages/design-system/src/styles/theme/oc-text.scss
Redesigns the tooltips so they are a bit smaller and hide when leaving the root element.
fixes https://github.com/opencloud-eu/web/issues/295
> feat: redesign tooltips

- packages/design-system/src/components/OcTextInputPassword/OcTextInputPassword.vue
- test case 1:
- test case 2:
- ...
> Don't show password while using generate password method

- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- test case 1:
- test case 2:
- ...
> Fix: edit space icon not centered

- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
Follow-up after #251 where we changed the snapping point of the right sidebar.
> fix: right sidebar snapping in app wrapper

- tests/e2e/cucumber/features/smoke/activity.feature
after https://github.com/opencloud-eu/web/pull/32/ the activities show the full name of the user. `Brian`, without the surname, also works fine because the test only uses `toContainText` at the end 
- needed for https://github.com/opencloud-eu/qa/issues/3
ran test case locally
> fix username in e2e test

- tests/e2e/cucumber/features/smoke/activity.feature
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
since #32 the activity will contain a random suffix to the user-name. This fixes the issue by allowing to check the string by using regular expressions
needed for https://github.com/opencloud-eu/qa/issues/3
ran test cases locally
> allow space activities be checked by regex

- packages/web-pkg/package.json
- packages/web-pkg/src/components/AppTopBar.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
- pnpm-lock.yaml
Same style fixes, namely:
1. Resource tile background was `surface` instead of `surface-container` when built trough `pnpm build` (was ok when built through `pnpm vite`).
2. Text editor long URLs were not collapsed in a production build (css class names for the selector are different in `pnpm build` and `pnpm vite`)
3. hover color on AppTopBar action buttons
> Style fixes

- tests/e2e/support/objects/app-files/share/collaborator.ts
file-action/groupActions.feature:7 
```
✖ And "Alice" shares the following resources using the sidebar panel # file:/woodpecker/src/github.com/opencloud-eu/opencloud/webTestRunner/tests/e2e/cucumber/steps/ui/shares.ts:23
| resource     | recipient | type  | role     |
| sharedFolder | Brian     | user  | Can edit |
| sharedFolder | Carol     | user  | Can edit |
| sharedFolder | David     | user  | Can edit |
| sharedFolder | Edith     | user  | Can edit |
| sharedFolder | sales     | group | Can edit |
| sharedFolder | finance   | group | Can edit |
| sharedFolder | security  | group | Can edit |
page.click: Timeout 30000ms exceeded.
Call log:
- waiting for locator('//span[contains(@class,"roles-select-role-item")]/span[text()="Can edit"]')
at Collaborator.setCollaboratorRole …
```
> e2e. fix collaboration sharing flaky

- packages/prettier-config/package.json
Declares `prettier` as a peer dependency because it's supposed to be provided by the user of this package. The package should only provide the config for it.
> chore(prettier-config): make prettier a peer dependency

- packages/web-app-files/src/components/SideBar/Details/FileDetailsMultiple.vue
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetailsMultiple.vue
Fixes the file, folder and space count in the right sidebar when selecting multiple items and refactors the components to script setup (separated into multiple commits to ease review).
fixes https://github.com/opencloud-eu/web/issues/351
> fix: file, folder and space count in right sidebar

- tests/e2e/support/objects/app-admin-settings/users/actions.ts
That fixes a problem when running against a posix storage because posix does not use the user ids as the personal space ids.
> Be less strict when waiting for the "change quota" responses

- packages/web-pkg/src/components/Search/ResourcePreview.vue
- packages/web-pkg/tests/unit/components/Search/ResourcePreview.spec.ts
Fixes an issue where loaded previews in the file list would be pixelated after using the search preview and refactors the component to script setup on the way.
fixes https://github.com/opencloud-eu/web/issues/370
> fix(pkg): pixelated previews after searching

- packages/web-runtime/src/components/Modals/AppTokenModal.vue
Since the app token passwords will be longer from now on, the modal was looking weird. Restyled it a little bit.
> feat(runtime): enhance app token modal copy view styling

- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Fixes the select all checkbox in the spaces tiles view so it also selects disabled spaces. We need to handle disabled spaces separately from disabled resources because they differ in behaviour.
Also refactors the `ResourceTiles` component to script setup.
fixes https://github.com/opencloud-eu/web/issues/354
> fix: select all checkbox in spaces tiles view

- packages/design-system/src/components/OcButton/OcButton.vue
- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
- packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
Allows copy pasting items into the current folder and refactors the component to script setup on the way. Also fixes an issue where disabled secondary buttons would have a hover effect.
fixes https://github.com/opencloud-eu/web/issues/371
> fix(files): copy pasting items into current folder

- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/tests/unit/components/FilesList/ResourceTile.spec.ts
- packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Adds the missing delete queue to the tiles view by also adding a loading state to the component. Refactors it to script setup on the way. This PR is best reviewed by its individual commits.
fixes https://github.com/opencloud-eu/web/issues/380
> fix(pkg): add missing delete queue to tiles view

- packages/design-system/src/helpers/types.ts
- packages/web-runtime/src/components/Account/AppTokens.vue
- packages/web-runtime/src/components/Modals/AppTokenModal.vue
- packages/web-runtime/tests/unit/components/Modals/AppTokenModal.spec.ts
This PR adds the `label` field of an app token to the creation modal (text input) and to the listing (table column) and adjusts tests accordingly.
Note: this needs an up to date OpenCloud backend, the last rolling is insufficient. The latest daily should work, otherwise you need to build your own OpenCloud image based on current main. This PR is the underlying prerequisite: https://github.com/opencloud-eu/opencloud/pull/433
- Fixes https://github.com/opencloud-eu/web/issues/392
- Unit tests
- Manual testing
> Make app token "label" field available to users

- packages/web-app-admin-settings/src/views/Spaces.vue
- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/AppBar/AppBar.vue
- packages/web-pkg/src/components/AppBar/CreateSpace.vue
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- packages/web-pkg/src/composables/piniaStores/spaces.ts
- packages/web-pkg/src/composables/resources/useLoadPreview.ts
- packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
- packages/web-pkg/tests/unit/composables/resources/useLoadPreview.spec.ts
Adds a loading indicator when space images are loading due to:
* regular page visit and images are not yet being cached
* image is being uploaded
* image has been uploaded and is temporarily stuck in post processing
Also refactors to script setup: `Projects.vue`, `SpaceHeader.vue`, `SpaceDetails.vue`
refs https://github.com/opencloud-eu/web/issues/361
> feat: space image loading indicator

- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
- packages/web-pkg/src/composables/piniaStores/spaces.ts
- packages/web-test-helpers/src/mocks/pinia.ts
Similar to https://github.com/opencloud-eu/web/pull/398 but for the space readme.
fixes https://github.com/opencloud-eu/web/issues/361
> feat: space readme loading indicator

- .woodpecker.star
we are not running that changelog pipeline and it actually do not exist anymore
- Fixes https://github.com/opencloud-eu/qa/issues/33
nothing to do
> delete last (skipped) call to changelog function

- .woodpecker.star
- tests/e2e/cucumber/features/app-store/details.feature
This PR enables the following e2e test pipelines to run in CI:
``` console
1. e2e-tests-1
2. e2e-tests-2
3. e2e-tests-3
4. e2e-tests-4
5. e2e-tests-oidc-iframe
6. e2e-tests-oidc-refresh-token
```
And also changes the version number in in `details.feature` to `1.0.0`.
- Part of: https://github.com/opencloud-eu/qa/issues/3
- Sub-Issue: https://github.com/opencloud-eu/qa/issues/23
- :robot:
> Enable e2e tests in CI

- .woodpecker.star
Check starlark didn't run on merge event. Since check starlark pipeline is in beforePipelines and unit tests depends on it, the unit tests didn't run on merge event.
https://ci.opencloud.eu/repos/6/pipeline/340
Follow up of PR https://github.com/opencloud-eu/web/pull/413
> fix unit test not running on merge event

- docker-compose.yml
- packages/web-app-external/src/App.vue
- packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
- packages/web-app-external/tests/unit/app.spec.ts
- packages/web-pkg/src/helpers/index.ts
- packages/web-pkg/src/helpers/spaces/index.ts
- packages/web-pkg/src/helpers/spaces/permissions.ts
- packages/web-pkg/src/services/folder/loaders/loaderSpace.ts
Fixes an issue where files that where shared with the "view" role had the secure view watermark. Also fixes Collabora in our dev setup.
This PR is best reviewed by commits.
fixes https://github.com/opencloud-eu/opencloud/issues/273#issuecomment-2750161660
> fix(external): shared files opening with secure view

- .woodpecker.star
the 'exclude' feature
(https://woodpecker-ci.org/docs/usage/workflow-syntax#path) does not seem to provide # what we need. It seems to skip the build as soon as one of the changed files matches an exclude pattern, we only # want to skip of ALL changed files match. So skip this condition for now:
This should just be a temporary fix until we figured out what's wrong with the `when` conditions. (See https://github.com/opencloud-eu/opencloud/pull/438 )
Same as https://github.com/opencloud-eu/opencloud/pull/439
> Disable the 'exclude' patterns on the path conditional for now

- docker-compose.yml
Adjusts the Collabora app name to "Collabora" in our dev setup since this gets displayed in the UI.
Follow-up of https://github.com/opencloud-eu/web/pull/418.
> chore: adjust Collabora app name

- packages/web-app-app-store/src/components/AppContextualHelper.vue
- packages/web-app-files/src/helpers/contextualHelpers.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
Removes links to dev docs that are not working currently. They need to be re-added later.
refs https://github.com/opencloud-eu/web/issues/429
> fix: remove invalid doc links

- packages/web-pkg/src/services/archiver.ts
Adds a chunking mechanism when creating blobs from the archiver because blobs have a limit of roughly 2GB. This ensures that larger archives can still be downloaded.
refs https://github.com/opencloud-eu/opencloud/issues/537
> fix: archive download with archives >2GB

- pnpm-lock.yaml
Fixes a recent dependabot security alert.
> chore(deps): bump @babel/runtime to v7.27.0

- packages/web-app-preview/src/components/MediaControls.vue
- packages/web-app-preview/tests/unit/components/MediaControls.spec.ts
Removes the zoom percentage to avoid confusion.
- Fixes #452
> fix: remove zoom indicator to avoid confusion

- tests/e2e/cucumber/environment/index.ts
- tests/e2e/support/api/davSpaces/spaces.ts
- tests/e2e/support/api/graph/spaces.ts
- tests/e2e/support/api/graph/userManagement.ts
- tests/e2e/support/api/http.ts
- tests/e2e/support/api/keycloak/openCloudUserToken.ts
- tests/e2e/support/api/keycloak/user.ts
- tests/e2e/support/api/keycloak/utils.ts
- tests/e2e/support/api/share/share.ts
- tests/e2e/support/api/token/utils.ts
This PR replaces the usage of node-fetch with Playwright’s request API
We no longer need to save cookies and send them in another request because playwright saves cookies in each context and reuses them
> [full-ci]use Playwright api instead of node fetch

- .woodpecker.star
This reverts commit 767877c6d1c7fb33cac37ad94176998b879b5301.
The exclude feature has been fixed in woodpecker 3.5.0
Partial fixes: https://github.com/opencloud-eu/qa/issues/37
> Revert "Disable the 'exclude' patterns on the path conditional for now"

- dev/scripts/create_and_push_tags.sh
We don't need this anymore since Web tagging if being handled by the release go bot.
> chore: remove web tag from tag create/push-script

- .woodpecker.star
This pipeline runs after ready-release-go, which generates the title and changelogs in the notes.
We don't want to overwrite the existing notes
- Fixes [#45](https://github.com/opencloud-eu/qa/issues/45)
@kulmann I think for testing you would have to create a new release with ready-release-go
> do not overwrite release when uploading artifacts

- packages/web-pkg/src/services/archiver.ts
- packages/web-pkg/src/services/client/client.ts
- packages/web-pkg/tests/unit/services/archiver.spec.ts
Axios seems to have problems with requests that exceed a certain size which results in data streams that can't be read. Use fetch instead to ensure big archives can still be downloaded.
This is a follow-up of https://github.com/opencloud-eu/web/pull/465.
refs https://github.com/opencloud-eu/opencloud/issues/537
> fix: use native fetch for downloading archives

- .woodpecker.star
Enable ready-release-go for the `stable-2.1` branch.
- relates to #526
> ci: enable ready-release-go for stable-2.1

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `2.1.1` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `stable-2.1` this pull-request will be updated.
- fix: use native fetch for downloading archives [[#525](https://github.com/opencloud-eu/web/pull/525)]
- fix: hide request-id when it's undefined [[#470](https://github.com/opencloud-eu/web/pull/470)]
- fix(files): truncation on long link names [[#489](https://github.com/opencloud-eu/web/pull/489)]
- fix: archive download with archives >2GB [[#467](https://github.com/opencloud-eu/web/pull/467)]
- Don't show …
> 🎉 Release 2.1.1

- .woodpecker.star
Picks https://github.com/opencloud-eu/web/pull/502 to the stable branch.
> ci: do not overwrite release when uploading artifacts

- packages/web-app-admin-settings/src/components/Groups/SideBar/MembersPanel.vue
- packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/MembersPanel.spec.ts.snap
Removed unnecessary oc-text-truncate to avoid the cut off inside the outline of the group member input field, when it has focus.
fixes: #540
> fix: removed unnecessary oc-text-truncate to avoid a cut off

- .woodpecker.star
- Makefile
- packages/design-system/docs/.vitepress/components/ComponentApi.vue
- packages/design-system/docs/.vitepress/config.ts
Adds a workflow for building and publishing the design-system to a branch called `design-system-docs`. From there it can be fetched and integrated by our Docusaurus docs.
refs https://github.com/opencloud-eu/web/issues/217
> ci: add workflow for design-system docs

- packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-files/src/views/spaces/Projects.vue
In case the quota of a space is unrestricted we want to show `Unrestricted` as remaining quota. We already do that in the space details. This PR changes it in the space overview of the files app and the space list in the admin settings.
My personal instance was showing 9.2 exabyte...
> fix: show remaining quota as unrestricted if quota is unrestricted

- packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
- packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
- packages/web-pkg/src/components/SideBar/SideBar.vue
This happens sometimes (for me anyway) when there are too many css animations on the screen. The loading spinner in the activities panels seems to have pushed this over a limit, hence only render the panel content if the panel is active. Also refactors the activity panel to script setup.
> fix: chrome oh snap errors

- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/src/index.ts
- packages/design-system/vite.config.ts
* Makes sure the css styles get bundled correctly so they can be imported via `@opencloud-eu/design-system/dist/design-system.css`.
* Externalize vue during build. This ensures that the components can be used properly when importing the design-system as a module in other projects. Vue is a peer dependency and needs to be provided by the host application.
> chore(design-system): bundle css & externalize vue

- packages/web-app-preview/src/App.vue
Opening previews was completely broken in share spaces because the `isDeleteButtonVisible` computed used the space before it's loaded.
> fix: opening previews in share spaces

- packages/web-pkg/src/components/AppBar/AppBar.vue
Bring back the left top rounded corner in the app bar.
> fix: bring back the left top rounded corner in the app bar

- packages/design-system/src/components/OcIcon/OcIcon.vue
- packages/design-system/src/helpers/icons.ts
- packages/design-system/src/helpers/index.ts
- packages/design-system/src/index.ts
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
This allows users of the design-system to specify a prefix for the icon loading. This might be useful when using it as a library.
> feat(design-system): add option for icon url prefix

- packages/web-pkg/src/helpers/resource/icon.ts
This will backport the following commits from `main` to `stable-2.1`:
- [fix: add missing icon for otp](https://github.com/opencloud-eu/web/pull/667)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
> [stable-2.1] fix: add missing icon for otp

- packages/design-system/src/components/OcButton/OcButton.vue
Fixes an issue where the text in filled `a` buttons would have the wrong color.
> fix(design-system): filled a button hover

- packages/design-system/src/components/OcTextInput/OcTextInput.vue
Follow-up of https://github.com/opencloud-eu/web/pull/686.
> fix(design-system): text input error message icon position

- packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
- packages/web-client/src/helpers/space/functions.ts
- packages/web-client/src/helpers/space/types.ts
- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- packages/web-pkg/src/composables/piniaStores/resources.ts
- packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
- packages/web-pkg/src/helpers/statusIndicators.ts
- packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
- packages/web-pkg/tests/unit/helpers/statusIndicator.spec.ts
We don't want to display this kind of information anymore due to performance reasons.
Also removes unnecessary `isMember` checks on project spaces since `/me/drives` only returns spaces where the current user is member of.
Preparation for https://github.com/opencloud-eu/web/issues/706
> feat: remove space membership info in file list

- packages/web-runtime/src/components/Account/AccountTable.vue
- packages/web-runtime/src/components/Account/AppTokens.vue
- packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
- Fixes #698 
- test case 1:
- test case 2:
- ...
> feat: polish account page design

- packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
- packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
- packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
- packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
- packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
- packages/web-pkg/src/components/Spaces/index.ts
- packages/web-pkg/src/composables/actions/files/useFileActionsSetImage.ts
- packages/web-pkg/tests/unit/components/Spaces/SpaceImageModal.spec.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetImage.spec.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- Fixes #709 
- test case 1:
- test case 2:
- ...
> feat: add cropping to space images

- packages/web-pkg/src/composables/actions/files/useFileActionsSetImage.ts
Component imports inside `web-pkg` should always reference components directly to avoid cyclic imports.
> fix: SpaceImageModal import

- dev/docker/opencloud/proxy.yaml
- dev/docker/radicale/config
- docker-compose.yml
- packages/design-system/src/components/OcTag/OcTag.vue
- packages/design-system/src/components/OcTag/__snapshots__/OcTag.spec.ts.snap
- packages/web-runtime/src/components/Account/CalDavUrl.vue
- packages/web-runtime/src/extensions.ts
- packages/web-runtime/tests/unit/components/Account/CalDavUrl.spec.ts
Added a Calendar Panel to the User Account Page.
This includes: CalDAV URL, username and an information about the Calendar-Implementaion.
This implements: https://github.com/opencloud-eu/web/issues/600
> feat: Added CalDAV URL to the Accountpage

- packages/web-runtime/src/components/Account/AppTokens.vue
- Followup #698 
- test case 1:
- test case 2:
- ...
> feat: polish account page followup

- packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
- packages/web-pkg/src/components/Avatars/AvatarUpload.vue
- packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
- packages/web-pkg/src/composables/keyboardActions/index.ts
- packages/web-pkg/src/composables/keyboardActions/useCropperKeyboardActions.ts
- packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts
- Fixes #804 
- test case 1:
- test case 2:
- ...
> feat: add keyboard support for space image and user avatar cropping

- packages/design-system/src/components/OcDrop/OcDrop.spec.ts
- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/web-pkg/src/components/ContextActions/ActionMenuDropItem.vue
- packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
- packages/web-pkg/src/components/ContextActions/ContextActionMenu.vue
- packages/web-pkg/src/components/ContextActions/ContextMenuQuickAction.vue
- packages/web-pkg/src/components/FilesList/ContextActions.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsNavigate.ts
- packages/web-pkg/tests/unit/components/ContextActions/ActionMenuDropItem.spec.ts
- packages/web-pkg/tests/unit/components/ContextActions/ContextActionMenu.spec.ts
- packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ActionMenuDropItem.spec.ts.snap
- packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
- Part of #773 
- test case 1:
- test case 2:
- ...
> test: add unit tests for context menu drop

- packages/web-pkg/src/helpers/statusIndicators.ts
- test case 1:
- test case 2:
- ...
> fix: tiles view accidentatly show space status indicators

- package.json
- pnpm-lock.yaml
- tests/e2e/cucumber/environment/index.ts
- tests/e2e/cucumber/environment/world.ts
- tests/e2e/cucumber/features/a11y/smoke.feature
- tests/e2e/cucumber/steps/ui/a11.y.ts
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/cucumber/steps/ui/session.ts
- tests/e2e/support/environment/actor/actor.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
- tests/e2e/support/objects/runtime/session.ts
- tests/e2e/support/utils/accessibility.ts
related #400 
This PR implements the checkAccessibility() function to check accessibility using e2e playwright tests with the following recommended rule tags: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'best-practice']
- Will it be a separate set of tests, or will we check a11e in existing tests? I would prefer to use existing e2e tests with the ability to enable/disable a11y tests (`A11Y_TEST=true`).
- Where to use `checkAccessibility()`
- check every click()
- check in specific places in action.ts files where page elements are clicked directly
- Failed tests:
- do not fail the test the first time. Just get the error logs
- further, during the fix, we can fail tests based on violation.impact (critical — test failed, moderate — test passed)
I experimented and wrapped each click with …
> A11y tests

- package.json
- tests/e2e/cucumber/steps/api.ts
- tests/e2e/cucumber/steps/ui/adminSettings.ts
- tests/e2e/cucumber/steps/ui/links.ts
- tests/e2e/cucumber/steps/ui/public.ts
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/cucumber/steps/ui/session.ts
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/support/objects/app-files/link/actions.ts
- tests/e2e/support/objects/app-files/link/index.ts
- tests/e2e/support/objects/app-files/page/public.ts
- tests/e2e/support/objects/app-files/page/shares/withMe.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
- tests/e2e/support/objects/app-files/share/index.ts
- tests/e2e/support/objects/app-files/share/utils.ts
- I added the command `pnpm check:unused-steps`, which compares all steps from `feature` and `stepDefinitions` files and finds unused steps that should, of course, be deleted.
example: 
```
pnpm check:unused-steps
> @3.0.0 check:unused-steps /Users/v.scharf/Work/opencloud/web
> TS_NODE_PROJECT=./tests/e2e/cucumber/tsconfig.json cucumber-js --profile=e2e --format usage --dry-run tests/e2e/cucumber/features/*/*.feature
(node:48694) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬────────────────────────────────────────────────────────────── …
```
> [full-ci] detect and delete unused steps

- .woodpecker.star
This value is not really secret and to show the URL of the tracing uploads or any other public artifacts we have to get rid of that secret as woodpecker masks all secret in the logs
needed for https://github.com/opencloud-eu/qa/issues/24
> get hostname of S3 server from var. not secret

- .woodpecker.star
- tests/e2e/cucumber/environment/index.ts
When a PR contains `with-tracing` in the heading or a test fails, the tracing results will be uploaded to a public S3 bucket, so that they can be used for debugging.
The cleanup will be done in #838
- Fixes https://github.com/opencloud-eu/qa/issues/24
- passing tests with `with-tracing` in the PR header
- failed tests without `with-tracing` in the PR header
> [with-tracing] Upload tracing results of UI tests to public S3

- packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
- test case 1:
- test case 2:
- ...
> fix: upload space image broken

- .woodpecker.star
This PR adds the following pipelines to purge the cache of `browsers`, `playwright-tracing-results` and `opencloud-build`:
- `purge-browser-build-cache`
- `purge-playwright-tracing-cache`
- `purge-opencloud-build-cache`
Check these previous CIs to see the cache being deleted:
- browser-cache: https://ci.opencloud.eu/repos/6/pipeline/2271/176 (Pipeline's name is not updated here.)
- playwright-tracing-results: https://ci.opencloud.eu/repos/6/pipeline/2286/179
- opencloud-build: https://ci.opencloud.eu/repos/6/pipeline/2261/175
- Related to: https://github.com/opencloud-eu/qa/issues/51
- :robot:
> [full-ci] flush all the build cache

- .woodpecker.star
- tests/e2e/cucumber/features/a11y/smoke.feature
- tests/e2e/cucumber/steps/ui/a11.y.ts
- tests/e2e/support/utils/accessibility.ts
- Added dedicated accessibility (a11y) test suite to CI pipeline
- Non-blocking: Tests detect and log accessibility violations but don't fail CI
> enable a11y tests in CI

- packages/design-system/src/tokens/ods/color.yaml
I noticed that some of the default colors for icons in the design system are not our theme default. Set them in the design system tokens now (where the defaults belong) and will delete them from the theme.json in the opencloud repo as soon as we brought a pre-release of web with the new defaults to the opencloud repo.
FTR: I just copied these colors:
https://github.com/opencloud-eu/opencloud/blob/df6fb3384f2089bade6c36a11497432f635cb570/services/web/assets/themes/opencloud/theme.json#L150
> fix(design-system): default colors for some of the icons

- packages/design-system/src/components/OcTable/OcTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
- packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
- packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
Reverting color hacks that deviated our design away from material design. Download new theme.json and logos and test with a docker-compose overlay:
```yaml
services:
opencloud:
environment:
WEB_ASSET_THEMES_PATH: ${WEB_ASSET_THEMES_PATH:-/web/themes}
WEB_UI_THEME_PATH: ${WEB_UI_THEME_PATH:-/themes/opencloud/theme.json}
volumes:
- ../web-theme/:/web/themes/opencloud/
```
Download the following files and move them to the `web-theme` folder (or whichever folder you mount into the dev stack)
[theme.json](https://github.com/user-attachments/files/21103982/theme.json)
Pre-requisite for merging our new theme in the opencloud repo, which will ultimately close https://github.com/opencloud-eu/web/issues/402 and works towards https://github.com/opencloud-eu/web/issues/513
> feat: revert material design color hacks

- tests/e2e/cucumber/features/spaces/project.feature
- tests/e2e/cucumber/steps/ui/spaces.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
tests for: 
- setting space image/icon using context menu
- deleting space image using context menu
> e2e tests. set space image using context menu

- Makefile
pnpm-lock.yaml contained cyclic imports
```bash
❯ pnpm install     
Scope: all 24 workspace projects
 WARN  There are cyclic workspace dependencies: /Users/fschade/Developer/fschade/opencloud-web/packages/design-system, /Users/fschade/Developer/fschade/opencloud-web/packages/web-test-helpers, /Users/fschade/Developer/fschade/opencloud-web/packages/web-pkg
✔ The modules directories will be removed and reinstalled from scratch. Proceed? 
```
> fix(pnpm): mute pnpm cyclic workspace dependencies warning in make

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
---
- Fixes #971 
- test case 1:
- test case 2:
- ...
> fix: markdown editor, adjust word break

- tests/e2e/support/objects/app-files/resource/actions.ts
Sometimes we get a double extension in tests.
> e2e-tests. clear input before fill name

- .woodpecker.star
This PR adds a new pipeline to enable sending CI notifications to a Matrix [channel](https://matrix.to/#/#opencloud-notifications:matrix.org).
- Part of: https://github.com/opencloud-eu/qa/issues/25
- :robot:
> [full-ci] add pipeline to send CI notifications to matrix-channel

- tests/e2e/support/objects/app-files/share/collaborator.ts
Fix flaky tests caused by right sidebar flickering when sharing with multiple users (issue not reproducible manually)
before: 
https://github.com/user-attachments/assets/8190367d-9ead-4839-accb-2d8346fc19f8
after: 
https://github.com/user-attachments/assets/d29f878d-84e2-4d15-ae48-788398821a0d
which tests were affected: 
`KEYCLOAK=true HEADLESS=false OC_BASE_URL=cloud.opencloud.test KEYCLOAK_HOST=keycloak.opencloud.test pnpm test:e2e:cucumber tests/e2e/cucumber/features/keycloak`
> e2e-test. fix share with multiple user test

- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/utils/editor.ts
The E2E tests for media viewer download and file closing were experiencing flakiness due to race conditions in Promise.all usage.
Applied Playwright's recommended "prepare promise first" pattern:
`HEADLESS=false pnpm test:e2e:cucumber:chromium tests/e2e/cucumber/features/shares/share.feature:79`
```
✔ And "Alice" opens the following file in mediaviewer                                    # file:/woodpecker/src/github.com/opencloud-eu/opencloud/webTestRunner/tests/e2e/cucumber/steps/ui/resources.ts:378
| resource       |
| test_video.mp4 |
✔ Then "Alice" is in a media-viewer                                                      # file:/woodpecker/src/github.com/opencloud-eu/opencloud/webTestRunner/tests/e2e/cucumber/steps/ui/public.ts:43
✔ When "Alice" downloads the following resource using …
```
> fix flaky close viewer after download

- packages/web-runtime/src/router/setupRouter.ts
- Part of #1030 
- test case 1:
- test case 2:
- ...
> feat: dispatch pathchange event for external integrations

- packages/design-system/src/components/OcModal/OcModal.vue
Prevents resources from getting deselected when closing modals. The ESC key should only close the modal in that case.
This also fixes an issue where the resource conflict dialog would not get focused again after closing it via ESC.
fixes https://github.com/opencloud-eu/web/issues/777
> fix: resource deselect when clicking esc in a modal

- dev/docker/opencloud/csp.yaml
- packages/web-pkg/src/components/SideBar/SideBar.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsToggleHideShare.ts
- packages/web-runtime/src/container/application/index.ts
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/tests/unit/container/bootstrap.spec.ts
While reviewing https://github.com/opencloud-eu/web-extensions/pull/166 we found out that the order of applications during application loading is not stable. Instead of coming up with a sorting/weight concept we've decided to just maintain a stable order. This PR does that with the least possible performance impact:
- loading application scripts happens in parallel
- only building and registering the applications happens one by one, with the order defined by the config.json (this ran in parallel before, but produced a random order)
- calling the `initialize` hook on all applications happens in parallel again
Manually and with the existing unit tests.
> fix extension registry stable order

- packages/web-app-files/src/HandleUpload.ts
- packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
- packages/web-app-files/src/helpers/directoryPicker.ts
- packages/web-app-files/tests/unit/HandleUpload.spec.ts
- packages/web-pkg/package.json
- packages/web-pkg/src/services/uppy/DropTarget/getDroppedFiles.ts
- packages/web-pkg/src/services/uppy/DropTarget/plugin.ts
- packages/web-pkg/src/services/uppy/DropTarget/types.ts
- packages/web-pkg/src/services/uppy/index.ts
- packages/web-pkg/src/services/uppy/uppyService.ts
- packages/web-pkg/src/services/uppy/utils.ts
- packages/web-pkg/tests/unit/services/uppy/DropTarget/getDroppedFiles.spec.ts
- packages/web-pkg/tests/unit/services/uppy/utils.spec.ts
- packages/web-runtime/package.json
- packages/web-runtime/src/components/UploadInfo.vue
- packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
- pnpm-lock.yaml
Introduces usage of the Directory API for uploading folders and replaces the Uppy drop target plugin by a custom one which is able to handle empty folders when uploading. Empty folders get added to the Uppy upload queue temporarily so they can be identified and processed by our `HandleUpload` plugin later down the line.
Note that uploading empty folders with non-Chromium browsers only works via drag&drop! Clicking the "Upload folder" button won't work with them because of browser limitations.
Also changes the upload overlay to only count root level files and folders. This prevents confusion where the overlay would show less items than the count. Furthermore, folders in the upload overlay are now clickable (again - I think this broke at some point).
closes …
> feat: preserve empty folders on upload

- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
fixes https://github.com/opencloud-eu/web/issues/1052
> fix: crippled search after leaving public link

- packages/web-runtime/src/App.vue
- packages/web-runtime/src/layouts/Application.vue
fixes https://github.com/opencloud-eu/web/issues/822 (thanks to @heijligen for providing the patch).
> fix: dynamic viewport height on mobile devices

- packages/web-app-preview/src/mimeTypes.ts
- packages/web-pkg/src/helpers/resource/icon.ts
As per title.
Fixes https://github.com/opencloud-eu/web/issues/1061
> feat(preview): add webp as supported mimetype

- packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
> test: fix unit test warnings

- packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
- packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
fixes https://github.com/opencloud-eu/web/issues/794
> fix: incoming group share name in sidebar

- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-pkg/src/composables/piniaStores/config/types.ts
- packages/web-runtime/src/container/bootstrap.ts
Renames the `defaultExtension` option to `defaultAppId` since that's a more appropriate name for the option. The old name comes from a time where we thought that we'd ship extensions individually, not piggyback with an app.
Idea came up in https://github.com/opencloud-eu/web-extensions/pull/177
> refactor: rename defaultExtension to defaultAppId

- packages/design-system/src/components/OcDefinitionList/OcDefinitionList.vue
- packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
Fixes regression from the current Tailwind migration.
> fix: font-weight in contextual helpers

- .woodpecker.star
The `design-system-docs` was a dependency of other pipelines, so they did not got triggered in cron job.
But that pipeline only needs to be run on `merge`.
So move the whole thing out and adjust the trigger.
pat of https://github.com/opencloud-eu/qa/issues/41
> run design-system-docs pipeline on cron

- packages/design-system/docs/.vitepress/components/LiveCodeBlock.vue
- packages/design-system/docs/.vitepress/config.ts
- packages/design-system/docs/.vitepress/theme/custom.scss
- packages/design-system/docs/.vitepress/theme/index.ts
- packages/design-system/docs/.vitepress/theme/tailwind.css
- packages/design-system/docs/components/OcRecipient/OcRecipient.md
- packages/design-system/package.json
- packages/design-system/src/styles/tailwind.css
- pnpm-lock.yaml
refs https://github.com/opencloud-eu/web/issues/937
> fix(design-system): docs after tailwind migration

- packages/web-pkg/src/composables/piniaStores/config/config.ts
- packages/web-runtime/src/components/Topbar/FeedbackLink.vue
We have a feedback survey now. This PR enables the feedback button in the topbar and sets our survey url as default. Also fixes the color of the button.
- Fixes https://github.com/opencloud-eu/web/issues/1135
> feat: enable feedback link and fix button color

- tests/e2e/cucumber/features/journeys/kindergarten.feature
- tests/e2e/cucumber/features/navigation/breadcrumb.feature
- tests/e2e/cucumber/features/oidc/refreshToken.feature
- tests/e2e/cucumber/features/search/search.feature
- tests/e2e/cucumber/features/shares/link.feature
- tests/e2e/cucumber/features/smoke/trashbinDelete.feature
- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/cucumber/features/spaces/project.feature
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/utils.ts
Tests were sometimes interrupted due to flaky `resourceExists()` function that used timeout-based element detection.
Restructured folder creation logic - if path contains '/' then parent folders already exist, just navigate inside. No timeouts, no try-catch, simple and stable.
> fix: remove flaky resourceExists

- packages/web-app-files/src/components/FilesViewWrapper.vue
- packages/web-app-files/src/components/SideBar/Audio/AudioMetaPanel.vue
- packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
- packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
- packages/web-pkg/src/components/AppTopBar.vue
- packages/web-pkg/src/components/FilesList/ResourceTiles.vue
- packages/web-pkg/src/components/SearchBarFilter.vue
- packages/web-pkg/src/components/SideBar/Spaces/SpaceInfo.vue
- packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap
- packages/web-runtime/src/components/Topbar/TopBar.vue
Also simplifies the topbar grid a bit and makes it work nicely on all screen resolutions (this includes the search icon not being placed in the middle of the screen).
refs https://github.com/opencloud-eu/web/issues/937
> refactor: migrate grid to tailwind

- packages/web-app-files/src/composables/extensions/useFolderViews.ts
- packages/web-pkg/src/components/ViewOptions.vue
- Fixes #1140 
- test case 1:
- test case 2:
- ...
> feat: add view mode switch to mobile view

- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/FilesList/ResourceTile.vue
fixed shortcut links in tiles view
Related to https://github.com/opencloud-eu/web/issues/1165
> fix: shortcut links not opening in tiles view

- packages/extension-sdk/index.mjs
You can still ship your manifest.json from public/, but instead you can also just put it next to your index.ts and have the extension-sdk insert the fingerprinted filename automatically. This way we can keep arbitrary values in the manifest.json while not disabling fingerprinting which is important for cache busting. If you do not provide any manifest.json, it's automatically generated now.
`pnpm build` creates fingerprinted assets, `pnpm build:w` creates assets without fingerprint. The latter is useful in development when serving the assets through opencloud directly, because manifest.json files are only read once on startup - if the filename is fingerprinted, opencloud needs to be restarted constantly
- test case 1:
- test case 2:
- ...
> feat: add manifest generator

- tests/e2e/support/objects/app-files/resource/actions.ts
Fix race condition when opening Collabora
Wait for load state, URL change, and response only after clicking Create button. Ensures Collabora is available before proceeding.
> fix mobile flaky test

- .woodpecker.star
- tests/e2e/cucumber/features/mobile-view/smoke.feature
remove flaky step create .`odt` file from mobile suite
> e2e-tests. remove create odt file from mobile suite

- tests/e2e/support/objects/app-files/utils/sidebar.ts
`await page.locator(closeSidebarSubPanelBtn).isVisible()` --> is FLAKY don't use it https://playwright.dev/docs/api/class-locator#locator-is-visible
- Fixes <https://github.com/opencloud-eu/qa/issues/67> 
- test case 1:
- test case 2:
- ...
> fix flaky. sharing test

- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
Removing the edit space description inline-button from the space header. It's supposed to be pretty for everyone, not only for those who can't edit the description. ;-) Also, aligning the button vertically is virtually impossible because it depends on the vertical paddings of the rendered content - which is different if some headline or block text is used.
> feat: remove edit space description inline button

- packages/web-pkg/src/composables/authContext/useRequest.ts
- packages/web-pkg/src/services/client/auth.ts
As authenticated user in a password protected public link context, the `makeRequest` method of the `useRequest` composable should use the password for authentication instead of the Bearer token.
refs https://github.com/opencloud-eu/opencloud/issues/1517
> fix: authenticated requests in password protected public links

- packages/design-system/src/components/OcDatepicker/OcDatepicker.spec.ts
- packages/design-system/src/components/OcDatepicker/OcDatepicker.vue
- packages/web-pkg/src/components/CreateLinkModal.vue
- packages/web-pkg/src/components/Filters/DateFilter.vue
- packages/web-pkg/src/components/Modals/DatePickerModal.vue
- packages/web-runtime/src/components/Modals/AppTokenModal.vue
- packages/web-runtime/tests/unit/components/Modals/AppTokenModal.spec.ts
Enables the dark mode for the date picker. **Note** this works with Chrome-Like browsers and Safari but not with Firefox 
- Fixes #1224 
- test case 1:
- test case 2:
- ...
> feat: add dark mode for OcDatePicker

- packages/design-system/docs/gettingStarted/installation.md
- packages/design-system/docs/gettingStarted/tailwindMigration.md
- packages/design-system/vite.config.ts
- packages/extension-sdk/index.mjs
- packages/extension-sdk/package.json
- pnpm-lock.yaml
This eliminates the need for each extension to do that on its own.
Also fixes the Tailwind import paths in the design-system docs and adds the missing css custom file.
refs https://github.com/opencloud-eu/web-extensions/issues/208
> feat(extension-sdk): add tailwind vite plugin to vite config

- packages/design-system/src/components/OcAvatars/OcAvatars.vue
- packages/design-system/src/components/OcTable/OcTable.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/tsconfig.json
- packages/web-pkg/vite.config.ts
fixes https://github.com/opencloud-eu/web-extensions/issues/220
> fix: add missing web-pkg types and fix type errors

- packages/web-pkg/src/apps/types.ts
- packages/web-pkg/src/composables/piniaStores/apps.ts
- packages/web-runtime/src/components/Topbar/TopBar.vue
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-runtime/src/index.ts
- packages/web-runtime/src/layouts/Application.vue
- packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
Loads the config a second time authenticated after the user has been loaded.
The acceptance criteria from the story can not be fulfilled because we need routes to load the auth context, and we need apps for the routes. Hence it's not possible to load the apps after the authenticated config. However, this doesn't seem to be needed because the `extensions` prop of an application is defined as a `ref` and is therefore reactive. That means checks on a user-specific config can still be made.
Also removes deprecated app properties.
closes https://github.com/opencloud-eu/web/issues/1050
> feat: load config authenticated

- tests/e2e/config.js
This PR updates the playwright timeout to fix the flaky test failure in nightly build as per the discusion in https://github.com/opencloud-eu/qa/issues/68
- Fixes https://github.com/opencloud-eu/qa/issues/68
- :robot:
> [full-ci][tests-only] Increase playwright timeout

- packages/web-pkg/src/components/AppTopBar.vue
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
- packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap
Fixes the topbar save icon on hover and prevents thumbnails from horizontally compressing in the file list on small screens.
Also refactors 2 components to script setup. Review by commits for an easier time.
Fixes https://github.com/opencloud-eu/web/issues/1279
> fix: topbar save icon hover color and thumbnail compression

- packages/web-app-admin-settings/src/components/Users/AddToGroupsModal.vue
- packages/web-app-admin-settings/src/components/Users/RemoveFromGroupsModal.vue
- packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
- packages/web-app-admin-settings/src/composables/actions/users/useUserActionsRemoveFromGroups.ts
- packages/web-app-admin-settings/tests/unit/components/Users/AddToGroupsModal.spec.ts
- packages/web-app-admin-settings/tests/unit/components/Users/RemoveFromGroupsModal.spec.ts
- packages/web-app-admin-settings/tests/unit/components/Users/SideBar/DetailsPanel.spec.ts
- packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsRemoveFromGroups.spec.ts
Only show relevant groups in user-group assignment. For removing groups, only show groups the user(s) are assigned to. For adding groups for one user, only show groups the uses is not already assigned to. For multiple users, we just show all groups because computing the intersection feels a bit overkill.
Also fixes the alignment in the user details panel and refactors some components to script setup.
fixes https://github.com/opencloud-eu/web/issues/1181
> fix: user group assignment options, details panel alignment

- packages/web-pkg/src/services/uppy/uppyService.ts
- packages/web-runtime/src/components/UploadInfo.vue
- packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
- web.d.ts
fixes https://github.com/opencloud-eu/web/issues/524
> fix: clean failed uploads when closing upload overlay

- packages/web-app-files/src/composables/extensions/useFolderViews.ts
- packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- packages/web-pkg/src/components/ViewOptions.vue
- Part of https://github.com/opencloud-eu/web/issues/1304
- test case 1:
- test case 2:
- ...
> feat: set view mode e.G tiles or table view  globally, add condensed view to Spaces view  

- packages/web-app-files/src/HandleUpload.ts
- packages/web-pkg/src/services/uppy/uppyService.ts
- packages/web-runtime/src/components/UploadInfo.vue
Uploading the same file multiple times while the upload is still running causes issues because Uppy can not distinguish those files. Hence prevent this behavior.
Also updates the file list immediately after a top-level folder has been created during upload so the user gets direct feedback about their upload.
fixes https://github.com/opencloud-eu/web/issues/1263
> fix: prevent uploading the same file again during upload

- packages/web-pkg/src/services/uppy/uppyService.ts
This makes Web independent of the current OS unicode normalization and prevents duplicated files and folders when using different OS with different unicode normalizations.
fixes https://github.com/opencloud-eu/web/issues/1261
> fix: normalize file and folder names to NFC when uploading
