opencloud-eu/web

- packages/extension-sdk/index.mjs
- packages/web-client/src/helpers/resource/functions.ts
- packages/web-client/src/helpers/resource/types.ts
- packages/web-client/src/webdav/client/builders.ts
- packages/web-client/src/webdav/client/dav.ts
- packages/web-client/src/webdav/index.ts
- packages/web-client/src/webdav/listFileVersions.ts
- packages/web-client/src/webdav/listFiles.ts
- packages/web-client/src/webdav/search.ts
- packages/web-client/src/webdav/types.ts
- packages/web-client/tests/unit/helpers/resource/functions.spec.ts
- packages/web-runtime/src/container/bootstrap.ts
- vite.config.ts
- test case 1:
- test case 2:
- ...
> Pick ext system improvements

- packages/design-system/docs/.vitepress/config.ts
> chore(design-system): include icons in docs bundle

- docker-compose.yml
- tests/e2e/cucumber/features/navigation/urlJourneys.feature
related: https://github.com/opencloud-eu/web/pull/32
we need start opencloud with `OC_SHOW_USER_EMAIL_IN_RESULTS=true` to find users by email. otherwise tests will failed
> add env to opencloud for local running e2e tests

- packages/design-system/docs/.vitepress/config.ts
- packages/design-system/docs/.vitepress/theme/custom.scss
- packages/design-system/docs/components/OcAvatar/OcAvatar.md
- packages/design-system/docs/components/OcAvatarCount/OcAvatarCount.md
- packages/design-system/docs/components/OcAvatarItem/OcAvatarItem.md
- packages/design-system/docs/components/OcAvatars/OcAvatars.md
- packages/design-system/docs/components/OcBreadcrumb/OcBreadcrumb.md
- packages/design-system/docs/components/OcButton/OcButton.md
- packages/design-system/docs/components/OcButton/handler.vue
- packages/design-system/src/tokens/ods/color.yaml
> docs(design-system): add docs for components a-b

- packages/design-system/docs/designTokens/colorPalette.md
- packages/design-system/docs/designTokens/fontSizes.md
- packages/design-system/docs/designTokens/sizeExamples.vue
- packages/design-system/docs/designTokens/spacings.md
> docs(design-system): beautify design tokens docs

- packages/design-system/docs/.vitepress/config.ts
- packages/design-system/docs/.vitepress/theme/custom.scss
- packages/design-system/docs/components/OcGrid/OcGrid.md
- packages/design-system/docs/components/OcHiddenAnnouncer/OcHiddenAnnouncer.md
- packages/design-system/docs/components/OcHiddenAnnouncer/default.vue
- packages/design-system/docs/components/OcIcon/OcIcon.md
- packages/design-system/docs/components/OcImage/OcImage.md
- packages/design-system/docs/components/OcInfoDrop/OcInfoDrop.md
- packages/design-system/docs/components/OcInfoDrop/list.vue
- packages/design-system/docs/components/OcList/OcList.md
- packages/design-system/docs/components/OcLoader/OcLoader.md
- packages/design-system/docs/components/OcLogo/OcLogo.md
- packages/design-system/docs/components/OcModal/OcModal.md
- packages/design-system/docs/components/OcModal/default.vue
- packages/design-system/docs/components/OcModal/input.vue
- packages/design-system/docs/components/OcModal/slot.vue
- packages/design-system/docs/components/OcNotificationMessage/OcNotificationMessage.md
- packages/design-system/docs/components/OcNotifications/OcNotifications.md
- packages/design-system/docs/components/OcPageSize/OcPageSize.md
- packages/design-system/docs/components/OcPageSize/default.vue
- packages/design-system/docs/components/OcPagination/OcPagination.md
- packages/design-system/docs/components/OcProgress/OcProgress.md
- packages/design-system/docs/components/OcProgressPie/OcProgressPie.md
- packages/design-system/src/components/OcGrid/OcGrid.spec.ts
- packages/design-system/src/components/OcGrid/OcGrid.vue
- packages/design-system/src/components/OcProgress/OcProgress.vue
- packages/design-system/src/components/OcProgressPie/OcProgressPie.vue
- packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
> docs(design-system): add docs for components g-p

- packages/design-system/docs/.vitepress/config.ts
- packages/design-system/docs/.vitepress/theme/custom.scss
- packages/design-system/docs/components/OcRadio/OcRadio.md
- packages/design-system/docs/components/OcRadio/default.vue
- packages/design-system/docs/components/OcRadio/group.vue
- packages/design-system/docs/components/OcRecipient/OcRecipient.md
- packages/design-system/docs/components/OcSearchBar/OcSearchBar.md
- packages/design-system/docs/components/OcSearchBar/advancedSearch.vue
- packages/design-system/docs/components/OcSearchBar/default.vue
- packages/design-system/docs/components/OcSearchBar/hiddenButton.vue
- packages/design-system/docs/components/OcSelect/OcSelect.md
- packages/design-system/docs/components/OcSelect/default.vue
- packages/design-system/docs/components/OcSelect/multiple.vue
- packages/design-system/docs/components/OcSpinner/OcSpinner.md
- packages/design-system/docs/components/OcStatusIndicators/OcStatusIndicators.md
- packages/design-system/docs/components/OcStatusIndicators/default.vue
- packages/design-system/docs/components/OcSwitch/OcSwitch.md
- packages/design-system/docs/components/OcSwitch/default.vue
- packages/design-system/docs/components/OcTable/OcTable.md
- packages/design-system/docs/components/OcTable/default.vue
- packages/design-system/docs/components/OcTable/disablingHighlighting.vue
- packages/design-system/docs/components/OcTable/slots.vue
- packages/design-system/docs/components/OcTableSimple/OcTableSimple.md
- packages/design-system/docs/components/OcTag/OcTag.md
- packages/design-system/docs/components/OcTag/linksHandlers.vue
- packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
> docs(design-system): add docs for components r-t

- packages/web-pkg/package.json
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- pnpm-lock.yaml
bugfix: sanitize content from md-editor
- test case 1:
- test case 2:
- ...
> Sanitize for md editor 

- packages/design-system/docs/.vitepress/config.ts
- packages/design-system/docs/components/OcCheckbox/OcCheckbox.md
- packages/design-system/docs/components/OcCheckbox/default.vue
- packages/design-system/docs/components/OcContextualHelper/OcContextualHelper.md
- packages/design-system/docs/components/OcContextualHelper/list.vue
- packages/design-system/docs/components/OcDatepicker/OcDatepicker.md
- packages/design-system/docs/components/OcDatepicker/default.vue
- packages/design-system/docs/components/OcDatepicker/handler.vue
- packages/design-system/docs/components/OcDefinitionList/OcDefinitionList.md
- packages/design-system/docs/components/OcDrop/OcDrop.md
- packages/design-system/docs/components/OcDropzone/OcDropzone.md
- packages/design-system/docs/components/OcEmojiPicker/OcEmojiPicker.md
- packages/design-system/docs/components/OcEmojiPicker/default.vue
- packages/design-system/docs/components/OcErrorLog/OcErrorLog.md
- packages/design-system/docs/components/OcFilterChip/OcFilterChip.md
- packages/design-system/docs/components/OcFilterChip/default.vue
- packages/design-system/docs/components/OcFilterChip/toggle.vue
- packages/design-system/src/components/OcDropzone/OcDropzone.vue
- packages/design-system/src/components/OcList/OcList.vue
> docs(design-system): add docs for components c-f

- packages/design-system/docs/components/OcApplicationIcon/OcApplicationIcon.md
- packages/design-system/src/components/OcApplicationIcon/OcApplicationIcon.vue
- test case 1:
- test case 2:
- ...
> Remove gradient from application menu

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- Fixes #206 
- test case 1:
- test case 2:
- ...
> Cut off long urls (including b64 images)

- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/ViewOptions.vue
- packages/web-pkg/src/composables/piniaStores/resources.ts
- packages/web-pkg/tests/unit/components/ViewOptions.spec.ts
- packages/web-runtime/src/container/bootstrap.ts
- packages/web-test-helpers/src/mocks/pinia.ts
- Fixes #213 
- Fixes #5 
- test case 1:
- test case 2:
- ...
> Move include disabled spaces to table settings

- packages/design-system/src/components/OcSelect/OcSelect.vue
- test case 1:
- test case 2:
- ...
> Replace oc-select chevron icon and align vertical

- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-client/src/helpers/space/functions.ts
- test case 1:
- test case 2:
- ...
> Fix sorting in spaces view may crash the application

- packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
- test case 1:
- test case 2:
- ...
> Fix: regex does not allow email addresses as username

- packages/web-app-admin-settings/tests/unit/components/Users/CreateUserModal.spec.ts
- test case 1:
- test case 2:
- ...
> Add unit test: allow email address as user name in user creation form

- packages/design-system/src/components/OcAvatarFederated/OcAvatarFederated.vue
- packages/design-system/src/components/OcAvatarGroup/OcAvatarGroup.vue
- packages/design-system/src/components/OcAvatarGuest/OcAvatarGuest.vue
- packages/design-system/src/components/OcAvatarItem/OcAvatarItem.vue
- packages/design-system/src/components/OcAvatarLink/OcAvatarLink.vue
- packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
- packages/design-system/src/components/OcButton/OcButton.vue
- packages/design-system/src/components/OcDrop/OcDrop.vue
- packages/design-system/src/components/OcIcon/OcIcon.vue
- packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
- packages/design-system/src/components/OcModal/OcModal.vue
- packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
- packages/design-system/src/components/OcSpinner/OcSpinner.vue
- packages/design-system/src/components/OcStatusIndicators/OcStatusIndicators.vue
- packages/design-system/src/components/OcTable/OcTable.vue
- packages/design-system/src/helpers/types.ts
- packages/web-pkg/src/helpers/resource/icon.ts
Adds some utility types for:
* appearance
* fill type
* size
* variation
closes https://github.com/opencloud-eu/web/issues/250
> refactor(design-system): utility types

- packages/web-app-files/src/views/spaces/GenericSpace.vue
- packages/web-client/src/helpers/space/functions.ts
- packages/web-client/src/helpers/space/types.ts
- packages/web-client/src/webdav/listFiles.ts
- packages/web-pkg/src/composables/piniaStores/auth.ts
- packages/web-runtime/src/index.ts
- packages/web-runtime/src/pages/resolvePublicLink.vue
Fixed referencing a non-existent field 🙈 
- Fixes https://github.com/opencloud-eu/opencloud/issues/308#issuecomment-2700122239
> fix: add publicLinkType to public space resource

- packages/web-pkg/tests/unit/composables/resources/useLoadPreview.spec.ts
- test case 1:
- test case 2:
- ...
> Fix useLoadPreview unit tests

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- test case 1:
- test case 2:
- ...
> Fix: auto focus on text editor not present

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- test case 1:
- test case 2:
- ...
> Add toolbar with undo and next to text editor

- packages/design-system/src/components/OcErrorLog/OcErrorLog.vue
- packages/design-system/src/components/OcTextInputPassword/OcTextInputPassword.vue
- packages/web-pkg/src/components/SideBar/WebDavDetails.vue
- packages/web-runtime/src/components/Modals/AppTokenModal.vue
- test case 1:
- test case 2:
- ...
> Increase copied to clipboard timeout

- packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
- test case 1:
- test case 2:
- ...
> Fix unit tests for upload info

- tests/e2e/config.js
I believe there is an `L` missing at the end of the name
needed for https://github.com/opencloud-eu/qa/issues/3
> fix typo in env variable

- packages/design-system/src/styles/theme/login.scss
- test case 1:
- test case 2:
- ...
> Fix jumpyness between login and plain view

- tests/e2e/cucumber/features/user-settings/languageChange.feature
- tests/e2e/support/environment/sse.ts
- skip language test. related https://github.com/opencloud-eu/opencloud/issues/369
- fix sse test
> fix e2e tests for CI

- .renovaterc.json
> Add default label to .renovaterc.json

- .woodpecker/release.yaml
- release-config.ts
```js
export default {
changeTypes: [
{
title: '💥 Breaking changes',
labels: ['breaking', 'Type:Breaking-Change'],
bump: 'major',
weight: 3,
},
{
title: '🔒 Security',
labels: ['security', 'Type:Security'],
bump: 'patch',
weight: 2,
},
{
title: '✨ Features',
labels: ['feature', 'Type:Feature'],
bump: 'minor',
weight: 1,
},
{
title: '📈 Enhancement',
labels: ['enhancement', 'refactor', 'Type:Enhancement'],
bump: 'minor',
},
{
title: '🐛 Bug Fixes',
labels: ['bug', 'Type:Bug'],
bump: 'patch',
},
{
title: '📚 Documentation',
labels: ['docs', 'documentation', 'Type:Documentation'],
bump: 'patch',
},
{
title: '✅ Tests',
labels: ['test', 'tests', 'Type:Tests'],
bump: 'patch',
},
{
title: '📦️ Dependencies',
labels: ['dependency', 'dependencies', 'Type:Dependencies'],
bump: 'patch',
weight: -1,
},
], …
```
> feat: add ready release go

- package.json
- packages/design-system/package.json
- packages/design-system/src/tokens/ods/role.yaml
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
- sonar-project.properties
Bump versions for the upcoming rolling release `v2.0.0`.
> Bump version to v2.0.0

- docker-compose.yml
posixfs will be the default storage driver in a few days. we want it now. :sunglasses:
> chore: switch dev stack to posixfs

- packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
- test case 1:
- test case 2:
- ...
> enhancement: show 'Personal' instead of username in right side bar

- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Fixes the invalid deletion date in the file details and refactors the component to script setup (separated into 2 commits to ease review).
fixes https://github.com/opencloud-eu/web/issues/357
> fix(files): deletion date in file details

- packages/web-pkg/src/components/ViewOptions.vue
- test case 1:
- test case 2:
- ...
> Fix: Show disabled spaces switch in wrong order

- packages/design-system/docs/components/OcList/OcList.md
- packages/design-system/src/components/OcList/OcList.vue
- packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
- packages/web-app-files/src/components/SideBar/Versions/FileVersions.vue
- packages/web-app-files/tests/unit/components/SideBar/__snapshots__/ActivitiesPanel.spec.ts.snap
- packages/web-runtime/tests/unit/components/Account/AppTokens.spec.ts
- test case 1:
- test case 2:
- ...
> Use oc-timeline for activities and versions panel 

- packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
- packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
Fixes the outline on the space member filter input and refactors the `SpaceMembers` component to script setup in the course.
fixes https://github.com/opencloud-eu/web/issues/353
> fix(files): outline on space member filter input

- packages/design-system/src/components/OcTextInputPassword/OcTextInputPassword.vue
fixes https://github.com/opencloud-eu/web/issues/372
> fix(design-system): jumpyness when focusing password input

- tests/e2e/support/objects/app-admin-settings/users/actions.ts
- tests/e2e/support/objects/app-admin-settings/users/index.ts
related #364
delete unused uuids
> delete unused uuids after fix #364

- packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/MembersPanel.spec.ts
- packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap
Similar to https://github.com/opencloud-eu/web/pull/368 but for the admin settings.
> fix(admin-settings): outline on space member filter input

- packages/design-system/src/components/OcTable/OcTable.vue
- packages/web-app-admin-settings/src/components/AppTemplate.vue
- packages/web-pkg/src/components/AppBar/AppBar.vue
- test case 1:
- test case 2:
- ...
> fix: table header overflows content

- packages/web-runtime/src/components/Topbar/UserMenu.vue
- packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
- test case 1:
- test case 2:
- ...
> feat: adjust avatar color in user menu

- packages/design-system/src/components/OcProgress/OcProgress.vue
- packages/design-system/src/components/OcProgress/__snapshots__/OcProgress.spec.ts.snap
- packages/web-pkg/src/components/SpaceQuota.vue
- packages/web-pkg/tests/unit/components/__snapshots__/SpaceQuota.spec.ts.snap
Fixes the space quota background color in the right sidebar and refactors the component to script setup on the way.
fixes https://github.com/opencloud-eu/web/issues/350
> fix(pkg): space quota background color

- packages/design-system/src/components/OcStatusIndicators/OcStatusIndicators.vue
- packages/design-system/src/components/OcTable/OcTable.vue
- packages/web-app-admin-settings/src/views/Spaces.vue
- packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
- packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
- packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
- packages/web-app-files/src/views/trash/Overview.vue
- packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceLink.vue
- packages/web-pkg/src/components/FilesList/ResourceListItem.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/components/LinkRoleDropdown.vue
- packages/web-pkg/src/components/ViewOptions.vue
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
- packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
- packages/web-runtime/src/components/Topbar/Notifications.vue
- packages/web-runtime/src/pages/accessDenied.vue
- packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
fixes https://github.com/opencloud-eu/web/issues/348
fixes https://github.com/opencloud-eu/web/issues/345
fixes https://github.com/opencloud-eu/web/issues/356
> fix: various hovers and small visual glitches

- .prettierignore
- .woodpecker.star
- packages/design-system/docs/components/OcList/OcList.md
- release-config.ts
- tests/e2e/support/objects/app-admin-settings/users/actions.ts
- tests/e2e/support/objects/app-files/spaces/actions.ts
- tests/e2e/support/objects/app-files/spaces/index.ts
- tests/woodpecker/csp.yaml
- runs `pnpm format:check` in CI and shows a diff if the format check failed
- fixes formatting issues
- Fixes https://github.com/opencloud-eu/qa/issues/32
:robot:
> check formatting in CI

- .woodpecker.star
build and release in CI. Most of the things are copied over from opencloud.
I haven't tested the tag workflow
- Fixes https://github.com/opencloud-eu/qa/issues/19
:robot:
> build and release in CI

- .woodpecker.star
Run unit tests in CI.
- Part of: https://github.com/opencloud-eu/qa/issues/3
- Fixes https://github.com/opencloud-eu/qa/issues/21
- test case 1:
- test case 2:
- ...
> setup unit test in CI

- .woodpecker.star
In this PR,
- test pipeline is made dependant to caching pipelines.
- changed `repo_slug` value to `opencloud-eu/web`
- renamed `build` pipeline to `build-release`
- https://github.com/opencloud-eu/qa/issues/3
- test case 1:
- test case 2:
- ...
> make tests depend on caching setps

- packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
fixes https://github.com/opencloud-eu/web/issues/388
> fix(files): hide 'Paste here' label with limited screen space

- packages/design-system/src/components/OcSelect/OcSelect.vue
fixes https://github.com/opencloud-eu/web/issues/349
> fix(design-system): align disabled select appearance with other inputs

- .woodpecker.star
- tests/e2e/support/api/external/openWithWeb.ts
Enabling `app-provider` tests.
- Part of: https://github.com/opencloud-eu/qa/issues/3
- Sub-issue: https://github.com/opencloud-eu/qa/issues/23
> [full-ci] enable app-provider tests

- .woodpecker.star
- release-config.ts
- test case 1:
- test case 2:
- ...
> Enable ready release go and use v prefix for tags

- .woodpecker.star
- tests/e2e/config.js
- tests/e2e/cucumber/steps/ui/shares.ts
- tests/e2e/support/environment/userManagement.ts
- tests/e2e/support/objects/federation/actions.ts
This PR enables `e2e-tests-ocm` pipeline in CI.
- Part of: https://github.com/opencloud-eu/qa/issues/3
- Sub-issue: https://github.com/opencloud-eu/qa/issues/23 
- :robot:
> [full-ci] enable `ocm` e2e tests pipeline

- .woodpecker.star
- release-config.ts
Fix the starlark syntax
- test case 1:
- test case 2:
- ...
> fix: starlark fix

- CHANGELOG.md
This PR was opened by the [ready-release-go](https://github.com/woodpecker-ci/plugin-ready-release-go) plugin. When you're ready to do a release, you can merge this pull-request and a new release with version `2.1.0` will be created automatically. If you're not ready to do a release yet, that's fine, whenever you add more changes to `main` this pull-request will be updated.
- feat(admin-settings): remove appearance section from General page [[#432](https://github.com/opencloud-eu/web/pull/432)]
- feat: space readme loading indicator [[#408](https://github.com/opencloud-eu/web/pull/408)]
- feat: space image loading indicator [[#398](https://github.com/opencloud-eu/web/pull/398)]
- feat: Make app token "label" field available to users [[#393](https://github.com/opencloud-eu/web/pull/393)]
- …
> 🎉 Release 2.1.0

- .woodpecker.star
- tests/e2e/support/api/keycloak/user.ts
- tests/e2e/support/environment/userManagement.ts
- tests/woodpecker/opencloud_keycloak/opencloud-ci-realm.dist.json
run e2e tests with keycloak
- part of https://github.com/opencloud-eu/qa/issues/23
- 
:robot:
> Setup keycloak service for e2e  tests in CI

- packages/web-app-admin-settings/src/components/General/InfoSection.vue
- packages/web-runtime/src/container/versions.ts
- packages/web-runtime/tests/unit/container/versions.spec.ts
- test case 1:
- test case 2:
- ...
> Don't show backend edition when not set

- docker-compose.yml
We have daily backend images now... switching the dev stack to that.
> chore: switch to daily backend image for dev stack

- packages/design-system/src/components/OcButton/OcButton.vue
- packages/web-runtime/src/pages/accessDenied.vue
- packages/web-runtime/src/pages/logout.vue
- packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
- Fixes #448 
- test case 1:
- test case 2:
- ...
> feat: change plain view button color

- packages/web-pkg/src/composables/piniaStores/messages.ts
refs https://github.com/opencloud-eu/web/issues/460
> fix: hide request-id when it's undefined

- packages/web-app-files/src/components/SideBar/Audio/AudioMetaPanel.vue
- packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
- packages/web-app-files/src/components/SideBar/Exif/ExifPanel.vue
- test case 1:
- test case 2:
- ...
> feat: make meta data panels more appealing

- packages/design-system/src/components/OcTable/OcTable.vue
- test case 1:
- test case 2:
- ...
> style: only add underline to oc table thead when table cell is sortable

- packages/web-app-files/src/views/spaces/Projects.vue
- test case 1:
- test case 2:
- ...
> fix: spaces overview item count

- packages/web-app-files/src/components/SideBar/Details/TagsSelect.vue
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- test case 1:
- test case 2:
- ...
> feat: add hint for tag searching

- packages/web-app-files/src/components/SideBar/Shares/Links/ListItem.vue
fixes https://github.com/opencloud-eu/web/issues/478
> fix(files): truncation on long link names

- .woodpecker.star
> delete unused variables

- .woodpecker.env
test with the current tip of main branch of opencloud
> [full-ci] bump opencloud commitid for tests

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
Bumping version to `2.2.0` for the upcoming rolling release.
> chore: bump version to v2.2.0

- .woodpecker.star
delete old cache files on the S3 server
- Fixes https://github.com/opencloud-eu/qa/issues/39
:robot:
> purge cache after every CI run

- .woodpecker.star
remove variables that are not used
part of https://github.com/opencloud-eu/qa/issues/46
:robot:
> [full-ci] remove unneeded variables

- packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
- Fixes #497 
- test case 1:
- test case 2:
- ...
> feat: adjust sidebar preview in the spaces view, so they look equal as the tiles

- .woodpecker.star
just fixing small issues my IDE complained about
:robot:
> remove unneeded parentheses

- .woodpecker.star
clean up things that we don't need
part of https://github.com/opencloud-eu/qa/issues/46
:robot:
> delete unneeded containers and directories

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
> chore: bump version to v2.1.1

- .woodpecker.star
This PR removes code duplication of event 
- Part of https://github.com/opencloud-eu/qa/issues/42
- CI
> [full-ci] Remove code duplication in CI

- packages/web-app-files/src/helpers/contextualHelpers.ts
- packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
Reintroducing partial links that have been removed via https://github.com/opencloud-eu/web/pull/430
- test case 1:
- test case 2:
- ...
> fix: reintroduce ct helper read more links

- README.md
> docs: fix 404 links in readme

- package.json
> chore: fix pnpm check:all command

- packages/web-app-text-editor/src/App.vue
Added padding to readonly-text-editor. 
fixes #539
> fix: added padding to readonly-text-editor

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
Bumps version to v2.3.0 for the upcoming rolling release.
> chore: bump version to v2.3.0

- .github/workflows/labels.yml
- test case 1:
- test case 2:
- ...
> PR label checker

- packages/web-app-preview/src/App.vue
- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- packages/web-pkg/src/composables/actions/files/useFileActionsDelete.ts
- packages/web-pkg/src/composables/actions/helpers/index.ts
- packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
- packages/web-pkg/src/composables/actions/helpers/useIsAppActive.ts
- packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
- tests/e2e/cucumber/features/file-action/delete.feature
- tests/e2e/cucumber/steps/ui/resources.ts
- tests/e2e/support/objects/app-files/resource/actions.ts
- tests/e2e/support/objects/app-files/resource/index.ts
- Fixes #592 
- test case 1:
- test case 2:
- ...
> feat: allow delete file within app

- packages/web-pkg/src/composables/actions/files/useFileActions.ts
- packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
- Fixes #614 
- test case 1:
- test case 2:
- ...
> fix:open in app action is available inside an app

- packages/web-app-files/src/components/Spaces/SpaceHeader.vue
- packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
- packages/web-pkg/src/components/TextEditor/TextEditor.vue
- Fixes #608 
- test case 1:
- test case 2:
- ...
> fix: space description has a grey background

- packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
- packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
- Fixes #613 
- test case 1:
- test case 2:
- ...
> fix: embed mode allows to choose locations that are not accessible

- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- Part of #631 
- test case 1:
- test case 2:
- ...
> fix: preview user cannot delete file in the shared with me page

- packages/web-app-preview/src/App.vue
- packages/web-app-preview/src/components/MediaControls.vue
- Fixes #631 
- test case 1:
- test case 2:
- ...
> fix: delete button in preview app media controls visible, even if permissions missions aren't granted

- packages/web-app-preview/src/App.vue
- packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
- test case 1:
- test case 2:
- ...
> fix: preview user cannot delete file in the shared with me page (followup)

- packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
- packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
- packages/web-pkg/src/components/SideBar/SideBar.vue
Picks https://github.com/opencloud-eu/web/pull/578 to the stable branch.
> fix: chrome oh snap errors

- tests/e2e/cucumber/features/smoke/upload.feature
- tests/e2e/support/utils/dragDrop.ts
- upload folder via drag and drop
- create separate scenario for insufficient quota
> upload folder via dragAndDrop

- packages/web-pkg/src/components/AppBar/AppBar.vue
backport of https://github.com/opencloud-eu/web/pull/647
> fix: bring back the left top rounded corner in the app bar

- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/vite.config.ts
closes https://github.com/opencloud-eu/web/issues/652
> feat(design-system): make component types available for lib usage

- packages/design-system/vite.config.ts
- vite.config.ts
> Asset bundling

- packages/web-pkg/src/helpers/resource/icon.ts
- test case 1:
- test case 2:
- ...
> fix: add missing icon for otp

- packages/design-system/src/tokens/ods/role.yaml
Wanted to align all color roles with the theme.json in the opencloud repo. Turned out, it was only primary and onPrimary which needed fixing. 🤷
> fix(design-system): adjust primary and onPrimary color roles

- .backportrc.json
To use https://github.com/sorenlouv/backport the added config file is required
this is how the package is working in action https://github.com/opencloud-eu/web/pull/670
- test case 1:
- test case 2:
- ...
> chore: add .backportrc.json

- packages/design-system/package.json
- packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
- packages/design-system/src/components/OcTextInput/OcTextInput.vue
- packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
- packages/web-runtime/package.json
- pnpm-lock.yaml
> chore(design-system): add missing portal-vue dependency

- docker-compose.yml
- test case 1:
- test case 2:
- ...
> chore: bump collabora to v25

- packages/design-system/package.json
> chore(design-system): prepare 2.4.0-alpha.1 release

- packages/design-system/src/components/OcColorInput/OcColorInput.vue
- packages/design-system/src/components/OcDatepicker/__snapshots__/OcDatepicker.spec.ts.snap
- packages/design-system/src/components/OcFileInput/OcFileInput.vue
- packages/design-system/src/components/OcSelect/OcSelect.vue
- packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
- packages/design-system/src/components/OcTextInput/OcTextInput.vue
- packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
- packages/design-system/src/styles/theme/oc-text.scss
- packages/design-system/types.d.ts
- packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
- tests/e2e/support/objects/app-files/link/actions.ts
* fix attr inheritance on file input
* remove focus expose on file input component
* fix input description and error message styling
* add missing type definitions for color and file inputs
* fix file input value binding
> fix: minor design system issues and styling

- packages/design-system/package.json
> chore(design-system): prepare 2.4.0-alpha.2 release

- packages/design-system/README.md
- packages/design-system/package.json
- packages/design-system/src/helpers/installOptions.ts
- packages/design-system/src/index.ts
- packages/design-system/vite.config.ts
> chore(design-system): make translations usable in library mode

- packages/design-system/package.json
> chore(design-system): prepare 2.5.0-alpha.1 release

- packages/web-pkg/src/composables/actions/spaces/useSpaceActionsSetIcon.ts
- test case 1:
- test case 2:
- ...
> chore: save space emoji as image.png

- packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
- packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
Before
After
- test case 1:
- test case 2:
- ...
> chore: adjust admin settings details panels

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
bump version to v3.0.0-alpha.1
> chore: bump version to v3.0.0-alpha.1

- packages/web-runtime/src/pages/logout.vue
- packages/web-runtime/src/router/index.ts
- packages/web-runtime/src/router/setupRouter.ts
- Fixes #778 
- test case 1:
- test case 2:
- ...
> fix: modal window doesn't close on browser navigation

- packages/web-app-files/src/views/spaces/Projects.vue
- packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceTable.vue
- packages/web-pkg/src/helpers/statusIndicators.ts
- Fixes #801 
- test case 1:
- test case 2:
- ...
> fix: status column appears multiple times

- pnpm-lock.yaml
Reverts opencloud-eu/web#781
Apparently this broke the build in CI (not locally?!). Needs further investigation.
> Revert "fix(deps): update dependency eslint-plugin-n to v17.19.0"

- package.json
- packages/design-system/package.json
- packages/eslint-config/package.json
- packages/extension-sdk/package.json
- packages/prettier-config/package.json
- packages/tsconfig/package.json
- packages/web-client/package.json
- packages/web-pkg/package.json
- packages/web-test-helpers/package.json
Bump version to `v3.1.0` for upcoming rolling release and for publishing packages.
> chore: bump version to v3.1.0 for the upcoming rolling release

- packages/web-app-files/src/views/trash/Overview.vue
- packages/web-app-files/tests/unit/views/trash/Overview.spec.ts
- packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
- packages/web-pkg/src/components/FilesList/ResourceIcon.vue
- packages/web-pkg/src/helpers/folderLink/types.ts
- tests/e2e/support/objects/app-files/trashbin/actions.ts
Before
After
- Requirement for #871 
- test case 1:
- test case 2:
- ...
>  chore: make use of resource-table in trashbin overview

- pnpm-lock.yaml
> chore(deps): bump pbkdf2 to 3.1.3 to fix CVE

- packages/web-app-preview/src/components/Sources/MediaImage.vue
Before 
After
- Fixes #1238 
- test case 1:
- test case 2:
- ...
> feat: add more screen real estate for images in preview app

- dev/docker/opencloud/csp.yaml
- packages/web-app-admin-settings/src/components/General/InfoSection.vue
- packages/web-client/src/ocs/capabilities.ts
- packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
- packages/web-runtime/src/components/VersionCheck.vue
- packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.ts
- packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
- packages/web-runtime/tests/unit/components/VersionCheck.spec.ts
- Fixes #1158 
- test case 1:
- test case 2:
- ...
> feat: add update check

- packages/web-pkg/src/components/TextEditor/TextEditor.vue
fixes https://github.com/opencloud-eu/web/issues/1331
> fix: disable echart loading in text editor
